repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
        args:
          - --allow-multiple-documents
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: terraform-format-check
        name: Terraform Format
        language: system
        entry: make tf-validate
        pass_filenames: false
        types: [terraform]
        stages: [pre-commit]
  - repo: local
    hooks:
      - id: terraform-validate
        name: Terraform Validate
        language: system
        entry: make tf-format-check
        pass_filenames: false
        types: [terraform]
        stages: [pre-commit]
  - repo: local
    hooks:
      - id: trivy-scan
        name: Trivy Scan
        language: system
        entry: make trivy-filesystem
        pass_filenames: false
        stages: [pre-commit]
